kaltura/playkit-js-providers

src/k-provider/ovp/loaders/data-loader-manager.js
src/k-provider/ovp/loaders/media-entry-loader.js
src/k-provider/ovp/loaders/session-loader.js
src/k-provider/ovp/loaders/ui-config-loader.js
src/k-provider/ovp/ovp-provider.js

Issue is due to provider code trying to define property called name on an object, which is not supported apparently on Safari on iOS9.

fix(FEC-6841): change getters called 'name' to 'id'

---

src/k-provider/ovp/provider-parser.js

Add support for extracting mimetype for sources without flavor ids
Main difference here is that we now always parse the metadata for mimetype if we can, but working on this has surfaced many issues I bet we didn't catch yet.
I won't add this here but need to think on making all object as object literals instead of class with contractor to simplify passing them around and add test for the declared use cases, such as VOD entry, VOD with DRM, Kaltura Live, external/universal live, e.g. which is a lot better then testing partner:entryid tests.

fix(FEC-7186): support external/universal live entries

---

.eslintrc.json
karma.conf.js
src/k-provider/ovp/ovp-provider.js
src/k-provider/ovp/services/stats-service.js
webpack.config.js

add export of name and version of library

feat: export name and version on module

---

src/k-provider/multi-request-builder.js
src/k-provider/ovp/ovp-provider.js
src/k-provider/ovp/provider-parser.js
src/util/logger.js
test/src/k-provider/ovp/ovp-provider.spec.js
yarn.lock

set to ERROR level by default
expose API to set and get log level and get log level enums
expose convenience method to set logger level via global window param `window.PLAYKIT_LOG_LEVEL`
update to JS-Logger V1.4

feat: expose logger API

---

flow-typed/types/media-info.js
src/k-provider/common/base-provider.js
src/k-provider/ott/provider-parser.js
src/k-provider/ott/provider.js
test/src/k-provider/ott/media-config-data.js
test/src/k-provider/ott/provider.spec.js

Support filtering sources by device formats such as in the SDK.
We need to pass a requestData object to the provider parser with the formats array.
It also passing context & media types for decide regards LIVE/VOD (will be supported soon). 
```js
var mediaInfo = {
entryId: 560216,
formats: ["HLSFPS_Mobile_SD", "HLS_360_SD"]
};
```

feat(ott-provider): filter sources by device formats

---

src/k-provider/ott/provider-parser.js
test/src/k-provider/ott/media-config-data.js

Return the correct media type from ott backend - LIVE (with/without DVR)/VOD.
Logic based on the SDK mobile logic.

feat(ott-provider): return media type (live/vod)

---

src/k-provider/ott/provider-parser.js
test/src/k-provider/ott/be-data.js
test/src/k-provider/ott/media-config-data.js
test/src/k-provider/ott/provider.spec.js

Fix the logic of checking live entry on OTT.
Now we're checking whether the response contains `externalIds` or its type of  `KalturaLinearMediaAsset`.
Logic is similar to [SDK logic](https://github.com/kaltura/playkit-android/blob/develop/playkit/src/main/java/com/kaltura/playkit/mediaproviders/ott/PhoenixMediaProvider.java#L484)

fix(FEC-7828): Live videos in OTT show VOD UI

---

src/k-provider/ott/provider-parser.js
test/src/k-provider/ott/media-config-data.js

changed the current structure of the metadata:
```
{
0: {key: "someKey",
value: "someValue"
},
1: {key: "someKey",
value: "someValue"
},
2: {key: "someKey",
value: "someValue"
},
..
}
```
to
```
metas: {
key1: value,
key2: value,
...
},
tags: {
key1: value,
key2: value,
...
}
```
* this also resolves the bug that some of the metas got overridden.

fix(FEC-8096): some of OTT metadata is getting overriden

---

src/k-provider/ovp/config.js

The default service URL is incorrect, but usually is taken from the API response so not used, so we probably didn't notice it.

fix: add "/api_v3" to default service URL

---

src/k-provider/ott/provider-parser.js

From Phoenix 5.1 
the API will result in new Object Type that expose live Media involved and should named "KalturaLiveAsset" instead of "KalturaLinearMediaAsset" that is not relevant any more.
As well as checking that externalIds not containing the string "0".

fix(FEC-8555): phoenix provider live detection

---

src/k-provider/ott/provider.js
src/k-provider/ovp/provider.js
test/src/k-provider/ovp/provider.spec.js

If session is only passed on `getMediaConfig` and on the provider constructor then the `isAnonymous` session flag is not set to false.

fix(FEC-8679): setting KS only on getMediaConfig counts as anonymous session

---

docs/configuration.md
flow-typed/types/provider-options.js
src/k-provider/common/base-provider.js
src/k-provider/common/data-loader-manager.js
src/k-provider/ott/loaders/data-loader-manager.js
src/k-provider/ott/provider.js
src/k-provider/ovp/loaders/data-loader-manager.js
src/k-provider/ovp/provider.js

fix flow type impact KalturaPlayerJS.
add missing retryNetwork configuration.

fix: 'networkRetryParameters' type causes KalturaPlayerJS build (flow) to fail

---

src/k-provider/ovp/external-captions-builder.js

change `caption.language` to `languageCode (instead of `language`)

fix(FEC-8858): the captions in languages list displayed twice

---

src/k-provider/ovp/external-captions-builder.js
test/src/k-provider/ovp/external-captions-builder.spec.js

use `webvtturl` when the caption format is DFXP or CAP.

feat(FEC-8875): when an external caption format is DFXP return the webvtt url

---

src/k-provider/ovp/play-source-url-builder.js

Removed the `extension` field from the mandatory params check, as in some use cases the fileExt are returning empty. 
In addition, added a check that will add the fileExt field if it exists.
- [V] changes have been done against master branch, and PR does not conflict
- [V] test are passing in local environment

fix(FEC-8935): Unable to play remote flavors

---

docs/configuration.md
flow-typed/types/network-retry-parameters.js
src/k-provider/common/base-provider.js
src/util/request-builder.js

default XHR request is async, but can be set to be sync.
If set to sync then don't allow setting timeout value to prevent error:
```
DOMException: Failed to set the 'timeout' property on 'XMLHttpRequest': Timeouts cannot be set for synchronous requests made from a document
```
new config option can be set under `networkRetryParameters`
```javascript
new playkit.providers.ovp.Provider(
{
partnerId: 12345, 
networkRetryParameters: {
async:false, 
timeout: 2000
}
}, 
'myPlayerVersion');
```

feat(FEC-8974): add async config option for XHR

---

src/k-provider/common/data-loader-manager.js
src/k-provider/ott/provider.js
src/k-provider/ovp/provider.js

The providers share the `_loadersResponseMap` on the statics of the provider and having multiple providers in different states may affect each other.
This also fixes an issue where provider saves KS from response of an anonymous request.

fix(FEC-8978): multiple players doing multi requests simultaneously may fail

---

src/k-provider/ovp/loaders/media-entry-loader.js
src/k-provider/ovp/services/base-entry-service.js
test/src/k-provider/ovp/provider.spec.js

support for redirectFromEntryId means when live is not available, provider will get the VOD entryId instead LIVE entryId.

fix(FEC-9212): support redirectFromEntryId logic

---

src/k-provider/common/base-provider.js
src/k-provider/ott/provider.js
src/util/error/code.js

* Implement `getPlaylistConfig`and `getEntryListConfig` in base provider which rejects with logical error
* fix `getMediaConfig` in base provider to rejects and not to throws as nobody catches the thrown 
* delete `_parseDataFromResponse` from base provider as it not needed (private)

fix(FEC-9304): OTT provider doesn't implement getPlaylistConfig api

---

src/k-provider/ovp/play-source-url-builder.js

OVP provider builds the play source manually. Till now it used the CDN Url as the domain for the playbacks. This works but is not correct. 
Changed the url to use serviceUrl (and needed to remove the api_v3)
OTT provider uses urls from server response.
solves FEC-10023

fix(FEC-10023): use serviceUrl instead of cdnUrl to create playback urls in V7

---

.travis.yml

Issue: providers repo doesn't have a canary build.
Solution: add build for every change on the master branch as we do on the Kaltura player.

build: create canary build on changes on master branch

---

src/k-provider/ovp/response-types/kaltura-bumper.js
test/src/k-provider/ovp/be-data.js
test/src/k-provider/ovp/media-config-data.js
test/src/k-provider/ovp/provider.spec.js

add `data.sources` existence protection 
solves FEC-10698

fix(FEC-10698): multi-request return entryId instead of sources, no playback

---

src/k-provider/ovp/external-captions-builder.js
src/k-provider/ovp/provider-parser.js
test/src/k-provider/ovp/be-data.js
test/src/k-provider/ovp/media-config-data.js
test/src/k-provider/ovp/provider.spec.js

issue: ks didn't add in the correct place.
solution: set the ks as a parameter on the end of URL and if the URL ended with / add the ks with slashes

fix(FEC-10722): add KS to external captions

---

src/k-provider/ott/provider-parser.js
test/src/k-provider/ott/provider-parser.spec.js

I switched the if else order to give precedence to KalturaLiveAsset enableTrickPlay
Updated tests accordingly 
solves FEC-10699

fix(FEC-10699): objectType KalturaLiveAsset should check enableTrickPlay for dvr before externalIds

---

src/k-provider/ovp/provider-parser.js

Issue: Crash on IE11 URL object doesn't exist.
Solution: check the extension without the URL object.

fix(FEC-11104): Crash on IE11 URL doesn't exist

---

src/k-provider/common/multi-request-builder.js
test/src/k-provider/ott/be-data.js
test/src/k-provider/ott/provider.spec.js

OTT invalid KS error is coming as object not as array so need to wrap it by array

fix(FEC-11363): OTT player doesn't get error for invalid KS

---

docs/configuration.md
flow-typed/types/provider-options.js

Add flag to provider configuration to allow ignoring server config.
Related PRs:
- https://github.com/kaltura/kaltura-player-js/pull/480
- https://github.com/kaltura/playkit-js-dual-screen/pull/29
Fixes FEC-11399.

feat(FEC-11399): allow ignoring server config

---

.travis.yml
flow-typed/types/media-config-metadata.js
src/k-provider/ott/provider-parser.js
src/k-provider/ott/services/bookmark/bookmark-service.js
test/src/k-provider/ott/be-data.js
test/src/k-provider/ott/media-config-data.js

save the epgId from provider response 
pass it as program ID parameter when sending a bookmark
related pr: 
https://github.com/kaltura/playkit-js-ott-analytics/pull/64
Solves FEC-11611

feat(FEC-11611): [Web] Pass the program ID when sending a bookmark

---

src/k-provider/common/base-provider.js
src/k-provider/common/data-loader-manager.js
src/k-provider/ovp/provider.js
test/src/k-provider/ovp/be-data.js
test/src/k-provider/ovp/provider.spec.js

**the issue:**
We are saving in provider only non-anonymous KS. When KS is then needed for BE requests, requests are failing.
Need to add KS to doRequest and keep ks for future API calls.
**solution:**
1. doRequest generates ks if doesn’t exist
2. doRequest should get external ks as parameter
Solves FEC-11696

feat(FEC-11696): add ks paramater in doRequest

---

src/k-provider/common/data-loader-manager.js
src/k-provider/common/multi-request-builder.js
src/k-provider/ott/provider.js
src/k-provider/ovp/provider.js
test/src/k-provider/ott/provider.spec.js
test/src/k-provider/ovp/provider.spec.js

Allow some of the entry list requests to fail without failing the entire multi request
Resolves FEC-11882

fix(FEC-11882): V3- Playlist/Related plugin - if entries list includes broken entry ID, the list doesn't load at all

---

src/k-provider/ovp/provider-parser.js
test/src/k-provider/ovp/provider-parser-data.js
test/src/k-provider/ovp/provider-parser.spec.js

**the issue:**
when playing simulive entry with external captions and the player fallbacks to real live stream - the captions from the simulive entry are displayed on the live stream.
**the solution:**
add captions source to the mediaEntry sources only if the media type is not live.
Note- needed to move fillBaseData before the if block in order to have mediaEntry.type initialized.
Solves FEC-12243

fix(FEC-12243): simulive - The live stream will show the captions from the Simulive entry

---

src/k-provider/ovp/provider.js

**the issue:**
if entry has a tag that contains 360 string with another characters for example: wells360fargo
the player activate the vr plugin even that is not 360 media.
**the root cause:**
the player activate the vr plugin if there is sequence of 360 in the list of the tags
**the solution:**
change the check that only if exists tag 360 without any other characters the vr plugin will be activated. 
solves: FEC-12588

fix(FEC-12588): 360 player loads whenever you have a tag that contains 360 (ie. wells360fargo)

---

.flowconfig
docs/configuration.md
flow-typed/types/env-config.js
flow-typed/types/provider-options.js
src/k-provider/ovp/config.js
src/k-provider/ovp/provider-parser.js
src/k-provider/ovp/provider.js
src/k-provider/ovp/regex-action-handler.js
src/k-provider/ovp/response-types/kaltura-access-control-modify-request-host-regex-action.js
test/src/k-provider/ovp/be-data.js
test/src/k-provider/ovp/media-config-data.js
test/src/k-provider/ovp/provider.spec.js
test/src/k-provider/ovp/regex-action-handler-data.js
test/src/k-provider/ovp/regex-action-handler.spec.js

add support for ECDN fallback upon inaccessible API gateway:
- make a ping request of the configured cdn to check if accessible
- the ping request should be executed only when there is accessControlActions configured with a regexAction
- we should apply the regex replacement if a ping was made and it was successful, or regexAction exists and there is no timeout configured
- add new configuration `provider.env.replaceHostOnlyManifestUrls` with default `false`, which indicates whether only playManifest urls should be applied with the regex; when configured to true- only play manifest urls should be replaced. if configured to false- in addition to manifest urls, apply the regex action to poster and captions urls
solves FEC-12850

feat(FEC-12850): ECDN Fallback Option Upon Inaccessible API Gateway

---

src/k-provider/ovp/services/analytics/analytics-service.js

**issue:** the request-builder retry mechanism `retryConfig.maxAttempts` parm set to 4 by default 
Therefore when it comes into action (for example in offline mode) it sends the same report 4 times in a row
**fix:** set retryConfig.maxAttempts to - 1 on Analytics-service
solves FEC-13146

fix(FEC-13146): Kava sent the View event 4 times

---

src/k-provider/ovp/provider.js

**the issue:**
when tag contains space and 360 it's activate the vr. the expected behavior is only if the tag is exact match to 360 the vr will be activated.
**the solution:**
check exact match to 360

fix(SUP-37445): Identifying tags that include 360 as 360 videos

---

src/k-provider/ovp/provider.ts

part of - https://github.com/kaltura/playkit-js-downloads/pull/46
[SUP-41001]: https://kaltura.atlassian.net/browse/SUP-41001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-41001): Download button not available

---

src/k-provider/ovp/regex-action-handler.ts
test/src/k-provider/ovp/regex-action-handler.spec.js

issue:
ecdn not working in V7 - the cdn urls are not changing as expected
fix:
revert the code to last version it worked - change async await back to promises and resolved
solved [SUP-42476](https://kaltura.atlassian.net/browse/SUP-42476)
[SUP-42476]: https://kaltura.atlassian.net/browse/SUP-42476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-42476):Bloomberg - Fallback not working player V7 eCDN

---

src/k-provider/common/base-provider.ts
src/k-provider/ovp/loaders/media-entry-loader.ts
src/k-provider/ovp/provider.ts
src/k-provider/ovp/services/base-entry-service.ts
src/types/provider-options.ts

feat(FEC-14049): add referrer to getPlaybackContext calls

---

src/k-provider/ovp/services/base-entry-service.ts

In case of iframe embed, the BE adds a parameter to the bundle window.originalRequestReferrer, this value will be added to api calls from the player to the backend for evaluation of access control request.
Issue:
The decision when to send it with API calls to the backend needs to be based if it was supplied in origin
Fix:
Send the referrer to the provider only if it was supplied by the backend
Resolves FEC-[https://kaltura.atlassian.net/browse/[FEC-14049](https://kaltura.atlassian.net/browse/FEC-14049)]
[FEC-14049]: https://kaltura.atlassian.net/browse/FEC-14049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14049): Send referrer only if it came from iFrame embed

---

src/entities/media-entry.ts
src/k-provider/ovp/provider-parser.ts
src/k-provider/ovp/provider.ts
src/k-provider/ovp/response-types/kaltura-media-entry.ts
src/types/media-config-sources.ts
src/types/media-entry.ts
test/src/k-provider/ovp/media-config-data.js

bugfix
**Issue:**
when building `poster` and `sprite` URLs, we are using the `poster` as the base url and then appending params to it (height, width, ks). But, when `poster` has already been manipulated and we try to build it again, we re-append the params.
**Fix:**
add a new field to the media config sources object, named `rawThumbnailUrl` which holds the raw url and can be used as the base url when building `poster` and `sprite`, instead of using the (manipulated) `poster`.
related PR: https://github.com/kaltura/kaltura-player-js/pull/830

fix(FEC-14071): thumbnail requests append height, width, ks too many times

---

src/k-provider/common/base-provider.ts
src/k-provider/ovp/config.ts
src/k-provider/ovp/provider.ts
src/k-provider/ovp/response-types/kaltura-user-get-response.ts
src/k-provider/ovp/services/user-service.ts
test/src/k-provider/ovp/media-config-data.js
test/src/k-provider/ovp/provider.spec.js

**Description of the Changes**
- Added a new service for Kaltura User Get using it inside the OVPProvider
- Concentrated the dealing with the flag config.session._isAnonymous in a single place in the file, instead of several places.
- Fixed the flag config.session._isAnonymous logic:
until now, config.session._isAnonymous was set to 'false' for every session that has ks (even if it's anonymous ks).
The fix insure that the flag config.session._isAnonymous will be set to 'false' only for sessions that have ks containing a valid user inside, otherwise the flag will be set to 'true'.
[FEC-14248]: https://kaltura.atlassian.net/browse/FEC-14248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14248): Anonymous session by user and not ks

---

src/k-provider/ovp/provider.ts

**Description of the Changes**
- Added a new service for Kaltura User Get using it inside the OVPProvider.
- Concentrated the dealing with the flag config.session._isAnonymous in a single place in the file, instead of several places.
- Fixed the flag config.session._isAnonymous logic:
until now, config.session._isAnonymous was set to 'false' for every session that has ks (even if it's anonymous ks).
The fix insure that the flag config.session._isAnonymous will be set to 'false' only for sessions that have ks containing a valid user inside, otherwise the flag will be set to 'true'.
[FEC-14248]: https://kaltura.atlassian.net/browse/FEC-14248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

fix(FEC-14248): Anonymous session by user and not ks + remarks

---

src/k-provider/ovp/provider.ts
src/types/provider-options.ts

**Issue:**
360 tag is being concat and playing 360VR video when no needed.
**Fix:**
Support new feature: Support a new configuration provider a new field of vrTag for custom tag.
Instead of compare the tags in the metadata to '360', compare it to the vrTag.
solved:
[SUP-46065](https://kaltura.atlassian.net/browse/SUP-46065)
[SUP-46065]: https://kaltura.atlassian.net/browse/SUP-46065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-46065): Player shows VR button based on "360" (or variations) tag

---

src/k-provider/common/base-provider.ts
src/k-provider/ovp/config.ts
src/k-provider/ovp/provider.ts
src/k-provider/ovp/response-types/kaltura-user-get-response.ts
src/k-provider/ovp/services/user-service.ts
test/src/k-provider/ovp/provider.spec.js

- Added a new service for Kaltura User Get using it inside the OVPProvider
- Concentrated the dealing with the flag config.session._isAnonymous in a single place in the file, instead of several places.
- Fixed the flag config.session._isAnonymous logic:
until now, config.session._isAnonymous was set to 'false' for every session that has ks (even if it's anonymous ks).
The fix insure that the flag config.session._isAnonymous will be set to 'false' only for sessions that have ks containing a valid user inside, otherwise the flag will be set to 'true'.
Related PR: https://github.com/kaltura/kaltura-player-js/pull/916
[FEC-14248]: https://kaltura.atlassian.net/browse/FEC-14248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

fix(FEC-14248): Anonymous session based on if ks contain user

---

src/k-provider/ovp/provider.ts
test/src/k-provider/ovp/provider.spec.js

- Fix for always adding ks as a parameter for 'OVPProviderParser.getMediaEntry' and 'OVPProviderParser.getBumper'.
Related PR: 
[259](https://github.com/kaltura/playkit-js-providers/pull/259)
[916](https://github.com/kaltura/kaltura-player-js/pull/916)
[FEC-14248]: https://kaltura.atlassian.net/browse/FEC-14248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14248): Anonymous session based on if ks contain user - fix

---

src/entities/media-entry.ts
src/k-provider/ovp/provider-parser.ts
src/k-provider/ovp/provider.ts
src/k-provider/ovp/request-params/base-entry-response-profile.ts
src/k-provider/ovp/response-types/kaltura-media-entry.ts
src/types/media-config-sources.ts
src/types/media-entry.ts
test/src/k-provider/ovp/be-data.js
test/src/k-provider/ovp/media-config-data.js
test/src/k-provider/ovp/provider-parser-data.js

- add `rootEntryId` and `capabilities` to the response profile of `baseEntry` service.
- fix tests
**related PRs:**
https://github.com/kaltura/playkit-js-reels/pull/23
https://github.com/kaltura/playkit-js-clip-to-parent/pull/1

feat(FEC-14439): Add link to original entry when playing a clip entry
