- src/k-provider/multi-request-builder.js
- src/k-provider/ott/services/ott-service.js
- src/k-provider/ovp/services/base-entry-service.js
- src/k-provider/ovp/services/meta-data-service.js
- src/k-provider/ovp/services/ovp-service.js
- src/k-provider/ovp/services/session-service.js
- src/k-provider/ovp/services/stats-service.js
- src/k-provider/ovp/services/ui-conf-service.js
- src/k-provider/request-builder.js
- src/util/param.js
- test/src/k-provider/ovp/services/stats-service.spec.js
- test/src/util/util.spec.js
support get method for stats service
> feat: support get method

- src/k-provider/ovp/config.js
- src/k-provider/ovp/loaders/data-loader-manager.js
- src/k-provider/ovp/ovp-provider.js
- src/k-provider/ovp/services/ovp-service.js
- src/k-provider/ovp/services/stats-service.js
- test/src/k-provider/ovp/ovp-provider.spec.js
- test/src/k-provider/ovp/services/stats-service.spec.js
remove clientTag from default config and get it as param
> fix(FEC-7123): remove clientTag from default config and get it as param

- CHANGELOG.md
- src/k-provider/ovp/config.js
- src/k-provider/ovp/provider-parser.js
- test/src/k-provider/ovp/player-config-parsed.js
check if the env (default or configured) contains the protocol. if not, take it from the `document.location.protocol`.
> fix(FEC-7389): player is not playing over https

- src/k-provider/common/base-service-result.js
- src/k-provider/ott/provider.js
Add protection from empty response + add error handling for ott response types.
> fix(FEC-7874): accessing undefined 'sources' property on bad request

- README.md
- docs/configuration.md
> docs: configuration

- src/k-provider/ovp/config.js
change the OVP provider default service config to cdsnapisec.kaltura.com
> fix(FEC-8135): change the provider default service config to cdsnapisec.kaltura.com

- flow-typed/types/media-config-metadata.js
- flow-typed/types/media-config-session.js
- flow-typed/types/media-config-sources.js
- flow-typed/types/media-config.js
- flow-typed/types/media-entry.js
- src/entities/media-entry.js
- src/k-provider/ott/provider-parser.js
- src/k-provider/ott/provider.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/provider.js
- test/src/k-provider/ott/media-config-data.js
- test/src/k-provider/ovp/media-config-data.js
Restructuring media config to:
```js
ProviderMediaConfigObject = {
session: ProviderMediaConfigSessionObject,
sources: ProviderMediaConfigSourcesObject,
plugins: { [plugin: string]: Object }
};
```
where:
```js
ProviderMediaConfigSessionObject = {
partnerId: number,
uiConfId?: number,
ks?: string
};
```
```js
ProviderMediaConfigSourcesObject = {
dash: Array<ProviderMediaSourceObject>,
hls: Array<ProviderMediaSourceObject>,
progressive: Array<ProviderMediaSourceObject>,
duration: number,
type: string,
id: string,
poster: string | Array<Object>,
dvr: boolean,
metadata: ProviderMediaConfigMetadataObject
};
```
```js
ProviderMediaConfigMetadataObject = {
name: string,
description: string
};
```
> feat(FEC-8176): restructure media config

- flow-typed/types/media-info.js
- src/entities/media-entry.js
- src/k-provider/ott/loaders/asset-loader.js
- src/k-provider/ott/provider.js
- src/k-provider/ott/response-types/kaltura-asset.js
- src/k-provider/ott/services/asset-service.js
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
> fix(FEC-8217): add asset reference for the asset get service

- src/k-provider/ott/config.js
remove default service url from OTT provider
> fix(FEC-8235): remove default service url from OTT provider and analytics

- src/util/request-builder.js
Add handling for invalid server response, as we assume that the response is always a valid JSON response
> fix(FEC-8316): protect against invalid server response

- src/k-provider/ott/provider.js
search the `360` tag under `metadata.metas.tags` instead of under `metadata.metas`
> fix(FEC-8499): OTT - entry not recognized as 360

- src/k-provider/common/response-types/kaltura-access-control-modify-request-host-regex-action.js
- src/k-provider/ovp/config.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/response-types/kaltura-playback-context.js
- test/src/k-provider/ovp/be-data.js
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider.spec.js
apply the request host regex on the playManifest urls
> feat(FEC-8730): add kaltura regex action support to providers

- flow-typed/types/provider-options.js
- src/k-provider/common/base-provider.js
- src/k-provider/ovp/loaders/session-loader.js
- src/k-provider/ovp/provider.js
- src/k-provider/ovp/services/session-service.js
- test/src/k-provider/ovp/provider.spec.js
Create OVP session with `widgetId` if exists. if no, use `_partnerId`.
> feat(FEC-8746): add wid parameter with the OVP provider

- flow-typed/types/provider-options.js
> chore: fix flow

- docs/configuration.md
> docs: 'useApiCaptions' flag

- src/k-provider/ott/response-types/kaltura-asset.js
add new enum for AssetReferenceType NPVR
> fix(FEC-9268): new enum for AssetReferenceType

- src/k-provider/ott/config.js
- src/k-provider/ott/response-types/kaltura-asset.js
> fix(FEC-9354): change apiVersion and fix asset type

- src/k-provider/common/base-provider.js
- src/k-provider/ovp/provider.js
- test/src/k-provider/ovp/provider.spec.js
> fix: widget id as anonymous

- src/entities/media-entry.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/provider.js
- src/k-provider/ovp/request-params/base-entry-response-profile.js
- src/k-provider/ovp/response-types/kaltura-media-entry.js
- src/util/error/code.js
- test/src/k-provider/ovp/be-data.js
- test/src/k-provider/ovp/provider-parser-data.js
- test/src/k-provider/ovp/provider.spec.js
Added a check in OVP provider to check status 0 or 1 from the multiRequest response and throw a specific new sub error 2002 of error 7002
solves FEC-8872
> feat(FEC-8872): add provider check for entry status import and converting

- src/k-provider/ovp/provider-parser.js
Add protection against empty xml field.
> fix(FEC-10394): Empty metadata xml field throws provider error

- .travis.yml
add commit after the build process.
> build: add commit after the build process.

- .travis.yml
> build: missing yarn in commit command

- src/k-provider/ovp/services/analytics/analytics-service.js
- test/src/k-provider/ovp/services/analytics-service.spec.js
add an optional param to send Kava beacons as POST
Solves FEC-10615
> feat(FEC-10615): support sending Kava beacons as POST

- src/entities/bumper.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/provider.js
- src/k-provider/ovp/response-types/kaltura-bumper.js
- src/k-provider/ovp/response-types/kaltura-playback-context.js
- test/src/k-provider/ott/media-config-data.js
- test/src/k-provider/ovp/be-data.js
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider.spec.js
parse bumper from playback context - OVP
Solves FEC-9142
> feat(FEC-9142): getting bumper from provider by entry Id (OVP)

- src/k-provider/ovp/external-captions-builder.js
- src/k-provider/ovp/provider-parser.js
- test/src/k-provider/ovp/be-data.js
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider.spec.js
Issue: ks missing for external captions.
Solution: add ks to external captions.
> fix(FEC-10722): ks missing for external captions

- src/util/logger.js
Issue: missing methods and properties for getLogger.
Solution: add the stubbing for all the methods and properties.
> fix(FEC-10779): add the all JSLogger for stubbing

- flow-typed/types/adapter-data-config.js
- flow-typed/types/media-info.js
- flow-typed/types/playback-context.js
- src/k-provider/ott/provider.js
- test/src/k-provider/ott/provider.spec.js
support adapterData for getPlaybackContext request
> feat(FEC-10804): add adapterData to getPlayback context request

- src/k-provider/ovp/index.js
> feat(FEV-1164): export ServiceResult

- src/k-provider/ovp/index.js
Export OVPProviderParser.
Resolves [FEC-11875](https://kaltura.atlassian.net/browse/FEC-11875)
Related PRs: 
https://github.com/kaltura/playkit-js-related/pull/4
https://github.com/kaltura/kaltura-player-js/pull/523
> feat(FEC-11875): Related Entries - Phase 2

- src/k-provider/common/multi-request-builder.js
> fix(FEC-12166): canary not working-error 1006

- flow-typed/types/media-config-metadata.js
- karma.conf.js
- src/k-provider/ott/config.js
- src/k-provider/ott/provider-parser.js
- src/k-provider/ott/response-types/kaltura-playback-context.js
- src/k-provider/ott/services/bookmark/bookmark-service.js
- test/src/k-provider/ott/media-config-data.js
> feat(FEC-12414):  add contextType to mediaEntry Metadata & upgrade API version 7.8.1

- .travis.yml
- src/k-provider/ott/provider-parser.js
- src/k-provider/ovp/provider-parser.js
- test/src/k-provider/ott/media-config-data.js
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider-parser-data.js
> feat(FEC-12625): add entry id to media metadata

- src/k-provider/ovp/provider-parser.js
> fix(FEC-12929): Add an image preview on "next-screen" in image item on playlist

- karma.conf.js
- package.json
- src/k-provider/ovp/regex-action-handler.js
- test/src/k-provider/ovp/regex-action-handler.spec.js
- yarn.lock
- fix 'should modify all URLs' test due to a broken ping request
- add test coverage to handleRegexAction scope
- enhance logic and clean code in RegexActionHandler class
Solves FEC-13113
> fix(FEC-13113): fix and add unit tests in handleRegexAction file

- src/k-provider/ovp/services/analytics/analytics-service.js
> fix(FEC-13146): Kava sent the View event 4 times - fix POST method

- src/k-provider/ott/provider-parser.js
- src/k-provider/ott/response-types/kaltura-asset.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/request-params/base-entry-response-profile.js
- src/k-provider/ovp/response-types/kaltura-media-entry.js
- test/src/k-provider/ott/media-config-data.js
> fix(FEC-13134): add ceratedAt and endedDate to media entry metadata if available

- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/request-params/base-entry-response-profile.js
- src/k-provider/ovp/response-types/kaltura-media-entry.js
… always holding the correct data
rollback FEC-13134
> fix(FEC-13241): Rollback - [WEB][Providers] - Player V7 - Playlist side panel does not open for Live entries

- flow-typed/types/media-config-sources.js
- flow-typed/types/media-entry.js
- src/entities/media-entry.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/provider.js
- src/k-provider/ovp/request-params/base-entry-response-profile.js
- src/k-provider/ovp/response-types/kaltura-media-entry.js
- test/src/k-provider/ovp/be-data.js
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider-parser-data.js
add downloadUrl to sources and mediaEntry.
> feat: Add download url

- flow-typed/types/media-config-metadata.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/request-params/base-entry-response-profile.js
- src/k-provider/ovp/response-types/kaltura-media-entry.js
solves: https://kaltura.atlassian.net/browse/FEC-13143
> fix(FEC-13143): add last update and ownerId to media metadata

- flow-typed/types/playlist.js
- src/entities/playlist.js
- src/k-provider/ott/provider.js
- src/k-provider/ovp/loaders/playlist-loader.js
- src/k-provider/ovp/provider-parser.js
- src/k-provider/ovp/provider.js
- src/k-provider/ovp/response-types/kaltura-user-entry-list-response.js
- src/k-provider/ovp/response-types/kaltura-user-entry.js
- src/k-provider/ovp/services/playlist-service.js
- test/src/k-provider/ovp/be-data.js
- test/src/k-provider/ovp/provider.spec.js
solves: https://kaltura.atlassian.net/browse/FEC-13450
> feat(FEC-13450): resume playlist from last entry

- src/k-provider/ovp/response-types/kaltura-media-entries.js
solves: https://kaltura.atlassian.net/browse/FEC-13566
> fix(FEC-13566): crashes on document entries in playlists.

- src/entities/doc-source.ts
- src/entities/document-source.ts
- src/entities/media-entry.ts
- src/entities/media-sources.ts
- src/k-provider/common/base-provider.ts
- src/k-provider/ott/provider.ts
- src/k-provider/ovp/provider-parser.ts
- src/k-provider/ovp/provider.ts
- src/k-provider/ovp/response-types/kaltura-media-entries.ts
- src/types/media-config-sources.ts
- src/types/media-sources.ts
- test/src/k-provider/ott/media-config-data.js
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider-parser-data.js
- test/src/k-provider/ovp/regex-action-handler-data.js
base PR: https://github.com/kaltura/playkit-js-doc-player/pull/1
solves: https://kaltura.atlassian.net/browse/FEC-13507
> feat(FEC-13507): support doc sources

- analytics-service/package.json
- bookmark-service/package.json
- ott-provider/package.json
- ovp-provider/package.json
- package.json
- playkit-analytics-service/package.json
- playkit-bookmark-service/package.json
- playkit-ott-provider/package.json
- playkit-ovp-provider/package.json
- playkit-stats-service/package.json
- stats-service/package.json
fix TypeScript mapping on IDEA
solves FEC-13604
> fix(FEC-13604): fix TypeScript mapping on IDEA

- analytics-service/package.json
- bookmark-service/package.json
- ott-provider/package.json
- ovp-provider/package.json
- package.json
- playkit-analytics-service/package.json
- playkit-bookmark-service/package.json
- playkit-ott-provider/package.json
- playkit-ovp-provider/package.json
- playkit-stats-service/package.json
- stats-service/package.json
include the new dir in npm publish
> include the new dir in npm publish

- package.json
- src/k-provider/ovp/provider-parser.ts
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider-parser-data.js
Add height to width ratio to media metadata
Also added test debug script
Resolves FEC-14047
> fix(FEC-14047):  add height to width ratio to media metadata

- src/k-provider/ovp/provider-parser.ts
- src/k-provider/ovp/response-types/kaltura-flavor-asset.ts
- src/util/object.ts
- test/src/k-provider/ovp/media-config-data.js
- test/src/k-provider/ovp/provider-parser-data.js
- test/src/k-provider/ovp/provider.spec.js
keep audio-flavors data inside media metadata
**Issue:**
resolves: https://kaltura.atlassian.net/browse/FEC-14087
> feat(FEC-14087): keep audio flavors data

- src/k-provider/ovp/response-types/kaltura-user-get-response.ts
**Description of the Changes**
Added option to handle guest/anonymous for empty string ''.
[FEC-14248]: https://kaltura.atlassian.net/browse/FEC-14248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-14248): Anonymous session by user and not ks

- src/k-provider/ovp/provider.ts
Reverts kaltura/playkit-js-providers#250
> Revert "fix(FEC-14248): Anonymous session by user and not ks + remarks"

- src/k-provider/ovp/response-types/kaltura-user-get-response.ts
Reverts kaltura/playkit-js-providers#252
> Revert "fix(FEC-14248): Anonymous session by user and not ks"

- docs/configuration.md
- src/k-provider/ovp/config.ts
- src/types/env-config.ts
> FEC-14359: add param to override service URL

- docs/configuration.md
- src/types/env-config.ts
> feat(FEC-14415): add path to initial call to kaltura server

- src/types/media-config-sources.ts
- src/types/provider-options.ts
- add `unisphereLoaderUrl` to provider config
- add `seekFrom` and `clipTo` to `ProviderMediaConfigSourcesObject` type
> chore: update config and type
